server:
  port: 8080
spring:
  datasource:
    initialization-mode: never
    password: espochpi3
    url: jdbc:postgresql://localhost/SGIO
    username: postgres
  jackson:
    time-zone:America/Guayaquil
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
